apiVersion: apps/v1
kind: Deployment
metadata:
  name: nolahmar-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nolahmar-playground
  template:
    metadata:
      labels:
        app: nolahmar-playground
    spec:
      containers:
        - name: nolahmar-playground
          image: nolahmar42/playground:v1
          ports:
            - containerPort: 8888
